### ISSUE TITLE
How do u add this as a dependency in build.gradle? Is this correct? 

### ISSUE THREAD

**Issue by gayathri-nair03** [AndroidDeveloperLB/ListViewVariants#3]

**Comment by AndroidDeveloperLB** [comment]
I didn't put it on gradle. Sorry.

**Comment by harinair** [comment]
Since many of you asked this, here is an easy trick. jitpack.io provides an easy gradle repo for all opensource projects.

Step 1: Add in your root build.gradle at the end of repositories:

```
    allprojects {
        repositories {
            ...
            maven { url "https://jitpack.io" }
        }
    }
```

Step 2: Add the dependency

If you want the latest from master:

```
    dependencies {
        compile 'com.github.AndroidDeveloperLB:ListViewVariants:-SNAPSHOT'
    }
```

or if you want a specific commit:

```
    dependencies {
            compile 'com.github.AndroidDeveloperLB:ListViewVariants:bca271a97b'
    }
```

To learn more go to: https://jitpack.io

**Comment by AndroidDeveloperLB** [comment]
@harinair Won't it import the sample stuff too?
I think you should change some stuff on the repo too.

**Comment by harinair** [comment]
@AndroidDeveloperLB Looks like it is really intelligent. It seems to be just building the library as an aar:
https://jitpack.io/com/github/AndroidDeveloperLB/ListViewVariants/ffb83e1019/build.log

Look at the POM:
https://jitpack.io/com/github/AndroidDeveloperLB/ListViewVariants/ffb83e1019/ListViewVariants-ffb83e1019.pom

**Comment by AndroidDeveloperLB** [comment]
@harinair You mean it took only the "library" folder ?

**Comment by harinair** [comment]
@AndroidDeveloperLB 
Yes - it looks like that.
